name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install package in dev mode
        run: python3 -m pip install -e .
      - name: Run tests
        run: python3 tests/test_icoutil.py
